### ISSUE TITLE
How to know and record which user to do the operation?

### ISSUE THREAD

**Issue by leven87** [indietyp/django-automated-logging#10]
Thanks for this amazing module. 
I have two questions:

1. How to know and record which user to do the operation, because I need to log the user's operation.

2. I could see you create several tables in the databse,  if you could further explain their meaning and relation that would be really helpful.

Thanks again!

**Comment by indietyp** [comment]
Hello, thanks for the questions.

**Disclaimer:** This information is current as of 6.0.0, but might change in the future - this disclaimer is mostly for people in the _future_

> Note to self: maybe move this into the README/wiki?

# Overview

The application has the following models:

* Application
* ModelMirror
* ModelField
* ModelEntry
* ModelEvent
* ModelValueModification
* ModelRelationshipModification
* RequestContext
* RequestEvent
* UnspecifiedEvent

The most important models/tables are:

* ModelEvent - saves model related changes
* RequestEvent - saves request related changes
* UnspecifiedEvent - saves other logging messages

ModelEvent and RequestEvent save the currently action user under the `user` field (FK). You can use that field to see which user did what action when.

The Application model keeps track of the different registered applications, there is [ContentTypes](https://docs.djangoproject.com/en/3.2/ref/contrib/contenttypes/) but it is insufficient for our usage, as it only keeps track of the current models in an application, meaning that if we would use that instead we would use logs for an application that was uninstalled - that behavior is undesirable.

# Unspecified Event

The unspecified event saves data for logging messages out of DAL scope and can be enabled/disabled via the configuration, it is standalone and saves data about the location and message. You can see the model [here](https://github.com/indietyp/django-automated-logging/blob/master/automated_logging/models.py#L330)

# Request Event

The request event is used in conjunction with the Request Context, if enabled it saves the content and content-type of the request, this can get very large very quickly so is disabled by default.

The RequestEvent has a lot of helpful data associated with it as you can see [here](https://github.com/indietyp/django-automated-logging/blob/master/automated_logging/models.py#L293)

# Model Event

The model event is a bit more complicated, but can be described roughly like this:
The main entry point is the [ModelEvent](https://github.com/indietyp/django-automated-logging/blob/master/automated_logging/models.py#L141), it stores the operation (delete = -1, modify = 0, create = 1), user, entry and if wanted the snapshot and performance statistics.

performance corresponds to the time taken for the operation, snapshot is a complete snapshot of the object. due to space concerns and slight overhead both are disabled by default but can be individually toggled.

The [ModelEntry](https://github.com/indietyp/django-automated-logging/blob/master/automated_logging/models.py#L106) keeps track of which actual entry was changed, we don't use `ContentTypes` here - due to the same problems as noted earlier, it saves a string representation and the primary key as well as the "mirror". There is always only one of these created per entry in your project and only if needed.

The [ModelMirror](https://github.com/indietyp/django-automated-logging/blob/master/automated_logging/models.py#L65) keeps track of the different models (not entries) in the project - their application and name. There is always only one of these created per model in your project - and only if needed.

To keep track of changes we use two different models that are associated with an event through a Many-To-Many relationship.
[ModelValueModification](https://github.com/indietyp/django-automated-logging/blob/master/automated_logging/models.py#L173), which keeps track of changes in "normal" fields and [ModelRelationshipModification](https://github.com/indietyp/django-automated-logging/blob/master/automated_logging/models.py#L221) which keeps track of changes in relationships.

## ModelValueModifcation

This keeps track of changes that happened to individual fields of an entry and uses [ModelField](https://github.com/indietyp/django-automated-logging/blob/master/automated_logging/models.py#L86) to keep track which field was used as well as a previous and current value (coerced to a string). The operation field indicated if the field was "created" (value changed from `None` to `A`), "modified" (value changed from `A` to `B`) or "deleted" (value changed from `A` to `None`).

## ModelRelationshipModification

This keeps track of changes that happened to a relationship. The operation field is here more important than in the ModelValueModification, while the operation value could be coerced pretty easily there this one functions to indicate what happened.

The entry indicated *which* entry was affected - and is never from the reverse side. Meaning if you have a Model `X` with an entry `y`, that has a reverse relationship to Model `A` and entry `b`, and you modify `y.reverse` to remove entry `b` (does not matter if FK or M2M) then it will record that `b.rel` (corresponding fictional relationship) removed `y`. This is to ensure integrity and easy data management. While you use the reverse relationship to do the operation, it is actually applied on the other side, DAL respects and reflects that change.

The operation `-1` (delete) indicates that `entry` was deleted from the relationship and `1` (create) indicates that `entry` was added to the relationship. `0` should never happen, but indicates that it just _changed_, this is here for future potential compatibility.


# Concluding Words

I hope this clears up some of your questions, if you have any more just let me know and I'll be happy to answer them.

**Comment by leven87** [comment]
Thanks for the reply.  While I check the tables automated_logging_requestevent, it does have a user_id field, but its values are all null. I'm not sure if I should configure in some place, or it relies on  django admin, as I'm not using admin.

**Comment by indietyp** [comment]
The user is fetched via a [Middleware](https://github.com/indietyp/django-automated-logging/blob/8948dcca85db93b58149cf6b868e127ba2ea4634/automated_logging/middleware.py#L110), you either haven't enabled the middleware or your user object is not accessible via the [Django request](https://docs.djangoproject.com/en/3.2/topics/auth/default/#authentication-in-web-requests)

The setup steps are described in [here](https://github.com/indietyp/django-automated-logging#setup). In particular (2) might be the problem in your case.

**Comment by leven87** [comment]
Thanks，I end up with create a new User Object myself.
